# Module: NumPy Assignments
## Lesson: NumPy


In [2]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [3]:
arr1 = np.random.randint(1,20,size = (5,5))
print(arr1)

[[ 3 16  4 10 10]
 [17  3 19  6  3]
 [ 3  1  5  4  5]
 [10 10 12  6 11]
 [19  4  4  7  7]]


In [4]:
arr1[:,2] = 1
print(arr1)

[[ 3 16  1 10 10]
 [17  3  1  6  3]
 [ 3  1  1  4  5]
 [10 10  1  6 11]
 [19  4  1  7  7]]



2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [5]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
np.fill_diagonal(arr1,0)
arr1

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [7]:
arr2 = np.arange(1,37).reshape(6,6)
print(f"Original array : \n {arr2}")

sub_arr2 = arr2[2:5,1:4]
print(f"Sub array \n {sub_arr2}")

Original array : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub array 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]



2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [20]:
arr2 = np.random.randint(1,20,size = (5,5))
print(f"Original array :\n {arr2}")

border = np.concatenate((arr2[0,:] , arr2[-1,:] , arr2[1:-1,0] , arr2[1:-1,-1]))
print(f"Border elements : \n {border}")

Original array :
 [[ 5 15 17 13 15]
 [ 9  6 18 18  7]
 [17  1  2  9 15]
 [ 5 12  1 10  3]
 [ 6  7  8 15  8]]
Border elements : 
 [ 5 15 17 13 15  6  7  8 15  8  9 17  5  7 15  3]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [10]:
arr3a = np.random.randint(1,10,size = (3,4))
arr3b = np.random.randint(1,10,size = (3,4))

print("Original arrays \n",arr3a,"\n",arr3b)

print("Element wise sum \n",arr3a+arr3b)
print("Element wise sub \n",arr3a-arr3b)
print("Element wise mult \n",arr3a*arr3b)
print("Element wise div \n",arr3a/arr3b)      # This may give Runtime error sometimes

print("Element wise division \n ", np.divide(arr3a,arr3b,where = True))

Original arrays 
 [[5 5 6 9]
 [9 3 3 8]
 [2 8 9 7]] 
 [[8 9 4 7]
 [7 2 8 8]
 [1 4 6 4]]
Element wise sum 
 [[13 14 10 16]
 [16  5 11 16]
 [ 3 12 15 11]]
Element wise sub 
 [[-3 -4  2  2]
 [ 2  1 -5  0]
 [ 1  4  3  3]]
Element wise mult 
 [[40 45 24 63]
 [63  6 24 64]
 [ 2 32 54 28]]
Element wise div 
 [[0.625      0.55555556 1.5        1.28571429]
 [1.28571429 1.5        0.375      1.        ]
 [2.         2.         1.5        1.75      ]]
Element wise division 
  [[0.625      0.55555556 1.5        1.28571429]
 [1.28571429 1.5        0.375      1.        ]
 [2.         2.         1.5        1.75      ]]



2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [11]:
arr3 = np.arange(1,17).reshape(4,4)

print(f"Original array :\n {arr3}")
row_wise = np.sum(arr3,axis=1)
column_wise = np.sum(arr3,axis=0)

print(f"row wise sum :\n {row_wise}")
print(f"column wise sum :\n {column_wise}")

Original array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row wise sum :
 [10 26 42 58]
column wise sum :
 [28 32 36 40]



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [12]:
arr4 = np.random.randint(1,20,size= (5,5))
print(f"Original array :\n {arr4}")

print(f"Mean : {np.mean(arr4)}")
print(f"Median : {np.median(arr4)}")
print(f"Standard Deviation : {np.std(arr4)}")
print(f"Variance : {np.var(arr4)}")


Original array :
 [[ 5 12 19 18  9]
 [10  1 14 11 11]
 [ 1 18  5 17  5]
 [15  2 16 10  1]
 [ 7 12  3  5 15]]
Mean : 9.68
Median : 10.0
Standard Deviation : 5.773872184245162
Variance : 33.3376



2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [19]:
normalized_arr = (arr4 - np.mean(arr4) )/ np.std(arr4)
print(normalized_arr)

# Formula : normalized arr = (arr - mean)/standard_deviation

print(f"Mean : {round(normalized_arr.mean())}")
print(f"Median : {np.median(normalized_arr)}")
print(f"Standard Deviation : {normalized_arr.std()}")
print(f"Variance : {normalized_arr.var()}")

[[-0.8105479   0.40181007  1.61416805  1.44097405 -0.11777192]
 [ 0.05542208 -1.50332389  0.74819807  0.22861608  0.22861608]
 [-1.50332389  1.44097405 -0.8105479   1.26778006 -0.8105479 ]
 [ 0.92139206 -1.33012989  1.09458606  0.05542208 -1.50332389]
 [-0.46415991  0.40181007 -1.1569359  -0.8105479   0.92139206]]
Mean : 0
Median : 0.055422078942648945
Standard Deviation : 1.0
Variance : 1.0



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [25]:
arr5 = np.random.randint(1,5,size=(3,3))
print(f"Original array :\n{arr5}\n")

_1d = np.arange(1,4)
print(f"1D array :\n{_1d}\n")


print(f"Result :\n{arr5+_1d}")    # Row wise broadcasting of _1d, _1d (3,)-->(3,3)

Original array :
[[1 2 4]
 [3 3 4]
 [1 4 3]]

1D array :
[1 2 3]

Result :
[[2 4 7]
 [4 5 7]
 [2 6 6]]



2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [27]:
arr5 = np.arange(1,17).reshape(4,4)
_1d = np.array([1,2,3,4])

print(arr5,"\n")
print(_1d,"\n")

print(f"Column wise subtraction : \n{arr5-_1d.reshape(4,1)}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[1 2 3 4] 

Column wise subtraction : 
[[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [29]:
arr6 = np.arange(1,10).reshape(3,3)
print(f"Origial matrix :\n{arr6}")


det = np.linalg.det(arr6)
eigenval = np.linalg.eigvals(arr6)
print(f"det :\n{det}")
print(f"eigen values :\n{eigenval}")
try :
    inv = np.linalg.inv(arr6)
    print(f"inverse :\n{inv}")
except Exception as error :
    print(error)


Origial matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
det :
0.0
eigen values :
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Singular matrix



2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [14]:
arr6_A = np.arange(1,7).reshape(2,3)
arr6_B = np.arange(1,7).reshape(3,2)
print(f"Array1 :\n{arr6_A}")
print(f"Array2 :\n{arr6_B}")

np.dot(arr6_A,arr6_B)

Array1 :
[[1 2 3]
 [4 5 6]]
Array2 :
[[1 2]
 [3 4]
 [5 6]]


array([[22, 28],
       [49, 64]])


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [15]:
arr7 = np.arange(1,10).reshape(3,3)
print(f"Original array: \n{arr7}")

reshaped_Arr = arr7.reshape(1,9)
print(f"Reshaped:\n{reshaped_Arr}")

again_reshaped = reshaped_Arr.reshape(9,1)
print(f"Final array:\n{again_reshaped}")

Original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped:
[[1 2 3 4 5 6 7 8 9]]
Final array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]



2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [19]:
arr7 = np.random.randint(1,10,size=(5,5))
print(f"Original array:\n{arr7}")

flatten_Arr = arr7.flatten()
print(f"Flatten array:\n{flatten_Arr}")

reshaped = flatten_Arr.reshape(5,5)
print(f"Reshaped: \n{reshaped}")

Original array:
[[3 1 4 6 7]
 [7 1 6 2 1]
 [8 3 3 1 9]
 [5 4 2 3 5]
 [7 4 3 5 6]]
Flatten array:
[3 1 4 6 7 7 1 6 2 1 8 3 3 1 9 5 4 2 3 5 7 4 3 5 6]
Reshaped: 
[[3 1 4 6 7]
 [7 1 6 2 1]
 [8 3 3 1 9]
 [5 4 2 3 5]
 [7 4 3 5 6]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [21]:
arr8 = np.random.randint(1,20,size = (5,5))
print(f"Original array :\n {arr2}")

extract = arr8[[0,0,-1,-1],[0,-1,0,-1]]
print(f"Elements on corner : \n {extract}")

Original array :
 [[ 5 15 17 13 15]
 [ 9  6 18 18  7]
 [17  1  2  9 15]
 [ 5 12  1 10  3]
 [ 6  7  8 15  8]]
Elements on corner : 
 [17 12  8 13]



2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [22]:
arr8 = np.random.randint(1,15,size=(4,4))
print(f"original array:\n{arr8}")

arr8[arr8>10]=10
print(f"Modified array:\n{arr8}")

original array:
[[13 10 12  8]
 [ 1 12  7  9]
 [ 5  5  6 13]
 [14 14 11  2]]
Modified array:
[[10 10 10  8]
 [ 1 10  7  9]
 [ 5  5  6 10]
 [10 10 10  2]]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.