# Module: NumPy Assignments
## Lesson: NumPy


In [1]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [5]:
arr1 = np.random.randint(1,20,size = (5,5))
print(arr1)

[[19 16 17  7  8]
 [ 5  9 16 15 13]
 [ 2  3  6  8 11]
 [18 10  2 17 15]
 [ 3 10 10 19 11]]


In [6]:
arr1[:,2] = 1
print(arr1)

[[19 16  1  7  8]
 [ 5  9  1 15 13]
 [ 2  3  1  8 11]
 [18 10  1 17 15]
 [ 3 10  1 19 11]]



2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [14]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
np.fill_diagonal(arr1,0)
arr1

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [20]:
arr2 = np.arange(1,37).reshape(6,6)
print(f"Original array : \n {arr2}")

sub_arr2 = arr2[2:5,1:4]
print(f"Sub array \n {sub_arr2}")

Original array : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub array 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]



2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [30]:
arr2 = np.random.randint(1,20,size = (5,5))
print(f"Original array :\n {arr2}")

border = np.concat((arr2[0,:] , arr2[-1,:] , arr2[1:-1,0] , arr2[1:-1,-1]))
print(f"Border elements : \n {border}")

Original array :
 [[14  1 17 19 17]
 [10  6  3 18  4]
 [19 16 17 10  9]
 [15  9  5  3 13]
 [ 9 16 17 11 19]]
Border elements : 
 [14  1 17 19 17  9 16 17 11 19 10 19 15  4  9 13]


In [21]:
arr2 = np.random.randint(1,20,size = (5,5))
print(f"Original array :\n {arr2}")

extract = arr2[[0,0,-1,-1],[0,-1,0,-1]]
print(f"Elements on corner : \n {extract}")

Original array :
 [[11 13 13  6 12]
 [18 14  5 18  3]
 [ 5  4 10 14  7]
 [ 3  5 16  4 17]
 [14  4  3 16  5]]
Elements on corner : 
 [11 12 14  5]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.